resources:
  - name: sources
    type: git
    source:
      uri: https://github.com/kalaiganeshan/Sample_Nodejs.git
      branch: master

jobs:
- name: test
  plan:
  - get: sources
    trigger: true
 # - task: install
 #   file: sources/pipeline/install.yml
  - task: test
    file: sources/pipeline/test.yml
